/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.*;
import clientgomoku.*;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author i-ONe
 */
public class Gomoku extends javax.swing.JFrame {
    private Client cli;
    private String Nickname;
    private int idUser;
    private String Roomname;
    private int RoomID;
    private ArrayList<String> RoomNameList = new ArrayList<String>();
    private ArrayList<Integer> RoomMemberList = new ArrayList<Integer>();
    private ArrayList<Integer> RoomCapacityList = new ArrayList<Integer>();
    private ArrayList<Integer> RoomIDList = new ArrayList<Integer>();
    private ArrayList<String> RoomMember = new ArrayList<String>();
    private int[][] Board = new int[20][20];
    private JButton[][] BoardUI = new JButton[20][20];
    private String WhoseTurn;
    private int[] NewMove = new int[2];
    private Socket cliSocket;
    private int idRoom;
    public DataOutputStream outToServer;
    public BufferedReader inFromServer;
    /**
     * Creates new form Gomoku
     */
    public Gomoku() {
        initComponents();
        MenuAwal.setVisible(true);
        PilihRoom.setVisible(false);
        MasukRoom.setVisible(false);
        Gameplay.setVisible(false);
        RoomNameList.add("hasi1");
        RoomMemberList.add(1);
        RoomCapacityList.add(5);
        RoomNameList.add("misal");
        RoomMemberList.add(4);
        RoomCapacityList.add(7);
        RoomNameList.add("contoh");
        RoomMemberList.add(3);
        RoomCapacityList.add(5);
        RoomMember.add("Try");
        RoomMember.add("Wawan");
        RoomMember.add("Ridwan");
        for (int i = 0; i < 20; i++){
            for (int j = 0; j < 20; j++){
                Board[i][j] = 0;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gomoku = new javax.swing.JLayeredPane();
        MenuAwal = new javax.swing.JPanel();
        PlayGameButton = new javax.swing.JLabel();
        ServerAddress = new javax.swing.JLabel();
        InsertServerAddress = new javax.swing.JTextField();
        Port = new javax.swing.JLabel();
        InsertPort = new javax.swing.JTextField();
        Port1 = new javax.swing.JLabel();
        InsertNickname = new javax.swing.JTextField();
        PilihRoom = new javax.swing.JPanel();
        ChooseRoom = new javax.swing.JLabel();
        CreateRoom = new javax.swing.JLabel();
        Or = new javax.swing.JLabel();
        ChooseRoomPane = new javax.swing.JScrollPane();
        InsideChooseRoomPane = new javax.swing.JPanel();
        CreateRoomDoor = new javax.swing.JLabel();
        RoomName = new javax.swing.JLabel();
        InsertRoomName = new javax.swing.JTextField();
        MaxPlayer = new javax.swing.JLabel();
        InsertMaxPlayer = new javax.swing.JTextField();
        CreateRoomButton = new javax.swing.JButton();
        MasukRoom = new javax.swing.JPanel();
        RoomTitle = new javax.swing.JLabel();
        PlayerListPane = new javax.swing.JScrollPane();
        InsidePlayerListPane = new javax.swing.JPanel();
        StartGame = new javax.swing.JLayeredPane();
        StartGameButtonDummy = new javax.swing.JButton();
        StartGameButton = new javax.swing.JButton();
        Gameplay = new javax.swing.JPanel();
        GOMOKU = new javax.swing.JLabel();
        RoomTitle1 = new javax.swing.JLabel();
        Turn = new javax.swing.JLabel();
        PlayerTurn = new javax.swing.JLabel();
        GameBoard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 560));
        setResizable(false);

        Gomoku.setPreferredSize(new java.awt.Dimension(960, 560));
        Gomoku.setLayout(new javax.swing.OverlayLayout(Gomoku));

        MenuAwal.setBackground(new java.awt.Color(153, 204, 255));
        MenuAwal.setPreferredSize(new java.awt.Dimension(960, 560));

        PlayGameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/playbutton.png"))); // NOI18N
        PlayGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PlayGameButtonMousePressed(evt);
            }
        });

        ServerAddress.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ServerAddress.setText("Server:");

        InsertServerAddress.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        InsertServerAddress.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InsertServerAddress.setToolTipText("");

        Port.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Port.setText("Port:");

        InsertPort.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        InsertPort.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InsertPort.setToolTipText("");

        Port1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Port1.setText("Nickname:");

        InsertNickname.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        InsertNickname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        InsertNickname.setToolTipText("");

        javax.swing.GroupLayout MenuAwalLayout = new javax.swing.GroupLayout(MenuAwal);
        MenuAwal.setLayout(MenuAwalLayout);
        MenuAwalLayout.setHorizontalGroup(
            MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAwalLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PlayGameButton)
                    .addGroup(MenuAwalLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ServerAddress)
                            .addComponent(Port)
                            .addComponent(Port1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InsertPort)
                            .addComponent(InsertServerAddress)
                            .addComponent(InsertNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        MenuAwalLayout.setVerticalGroup(
            MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAwalLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(PlayGameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ServerAddress)
                    .addComponent(InsertServerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Port)
                    .addComponent(InsertPort, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Port1))
                .addGap(58, 58, 58))
        );

        Gomoku.add(MenuAwal);

        PilihRoom.setBackground(new java.awt.Color(153, 204, 255));
        PilihRoom.setPreferredSize(new java.awt.Dimension(960, 560));

        ChooseRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/chooseRoom.png"))); // NOI18N

        CreateRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/createRoom.png"))); // NOI18N

        Or.setFont(new java.awt.Font("Stencil Std", 0, 36)); // NOI18N
        Or.setText("or");

        ChooseRoomPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        InsideChooseRoomPane.setBackground(new java.awt.Color(204, 204, 255));
        InsideChooseRoomPane.setForeground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout InsideChooseRoomPaneLayout = new javax.swing.GroupLayout(InsideChooseRoomPane);
        InsideChooseRoomPane.setLayout(InsideChooseRoomPaneLayout);
        InsideChooseRoomPaneLayout.setHorizontalGroup(
            InsideChooseRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        InsideChooseRoomPaneLayout.setVerticalGroup(
            InsideChooseRoomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        ChooseRoomPane.setViewportView(InsideChooseRoomPane);

        CreateRoomDoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/door.png"))); // NOI18N

        RoomName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RoomName.setText("Room Name:");

        InsertRoomName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InsertRoomName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MaxPlayer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MaxPlayer.setText("Max. Player:");

        InsertMaxPlayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InsertMaxPlayer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CreateRoomButton.setBackground(new java.awt.Color(153, 153, 255));
        CreateRoomButton.setFont(new java.awt.Font("Segoe WP Black", 0, 18)); // NOI18N
        CreateRoomButton.setText("CREATE");
        CreateRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PilihRoomLayout = new javax.swing.GroupLayout(PilihRoom);
        PilihRoom.setLayout(PilihRoomLayout);
        PilihRoomLayout.setHorizontalGroup(
            PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihRoomLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PilihRoomLayout.createSequentialGroup()
                        .addComponent(ChooseRoom)
                        .addGap(162, 162, 162)
                        .addComponent(Or))
                    .addComponent(ChooseRoomPane, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PilihRoomLayout.createSequentialGroup()
                        .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MaxPlayer)
                            .addComponent(RoomName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsertRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsertMaxPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateRoomButton))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PilihRoomLayout.createSequentialGroup()
                        .addComponent(CreateRoomDoor)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PilihRoomLayout.createSequentialGroup()
                        .addComponent(CreateRoom)
                        .addGap(36, 36, 36))))
        );
        PilihRoomLayout.setVerticalGroup(
            PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihRoomLayout.createSequentialGroup()
                .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PilihRoomLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChooseRoom)
                            .addComponent(CreateRoom, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PilihRoomLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Or)))
                .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PilihRoomLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateRoomDoor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsertRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PilihRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsertMaxPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaxPlayer))
                        .addGap(18, 18, 18)
                        .addComponent(CreateRoomButton)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PilihRoomLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChooseRoomPane, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        Gomoku.add(PilihRoom);

        MasukRoom.setBackground(new java.awt.Color(153, 204, 255));
        MasukRoom.setPreferredSize(new java.awt.Dimension(960, 560));

        RoomTitle.setFont(new java.awt.Font("Segoe WP Black", 0, 36)); // NOI18N
        RoomTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomTitle.setText("jLabel1");

        PlayerListPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        InsidePlayerListPane.setBackground(new java.awt.Color(204, 204, 255));
        InsidePlayerListPane.setForeground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout InsidePlayerListPaneLayout = new javax.swing.GroupLayout(InsidePlayerListPane);
        InsidePlayerListPane.setLayout(InsidePlayerListPaneLayout);
        InsidePlayerListPaneLayout.setHorizontalGroup(
            InsidePlayerListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        InsidePlayerListPaneLayout.setVerticalGroup(
            InsidePlayerListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        PlayerListPane.setViewportView(InsidePlayerListPane);

        StartGame.setLayout(new javax.swing.OverlayLayout(StartGame));

        StartGameButtonDummy.setFont(new java.awt.Font("Segoe WP Black", 0, 18)); // NOI18N
        StartGameButtonDummy.setForeground(new java.awt.Color(204, 204, 204));
        StartGameButtonDummy.setText("START GAME");
        StartGame.add(StartGameButtonDummy);

        StartGameButton.setFont(new java.awt.Font("Segoe WP Black", 0, 18)); // NOI18N
        StartGameButton.setText("START GAME");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });
        StartGame.add(StartGameButton);

        javax.swing.GroupLayout MasukRoomLayout = new javax.swing.GroupLayout(MasukRoom);
        MasukRoom.setLayout(MasukRoomLayout);
        MasukRoomLayout.setHorizontalGroup(
            MasukRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MasukRoomLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(PlayerListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MasukRoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        MasukRoomLayout.setVerticalGroup(
            MasukRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasukRoomLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(RoomTitle)
                .addGap(67, 67, 67)
                .addComponent(PlayerListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        Gomoku.add(MasukRoom);

        Gameplay.setBackground(new java.awt.Color(153, 204, 255));
        Gameplay.setPreferredSize(new java.awt.Dimension(960, 560));

        GOMOKU.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        GOMOKU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GOMOKU.setText("GOMOKU");

        RoomTitle1.setFont(new java.awt.Font("Shonar Bangla", 0, 24)); // NOI18N
        RoomTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoomTitle1.setText("jLabel1");

        Turn.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        Turn.setText("TURN:");

        PlayerTurn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        PlayerTurn.setText("playername");

        javax.swing.GroupLayout GameBoardLayout = new javax.swing.GroupLayout(GameBoard);
        GameBoard.setLayout(GameBoardLayout);
        GameBoardLayout.setHorizontalGroup(
            GameBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        GameBoardLayout.setVerticalGroup(
            GameBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GameplayLayout = new javax.swing.GroupLayout(Gameplay);
        Gameplay.setLayout(GameplayLayout);
        GameplayLayout.setHorizontalGroup(
            GameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameplayLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(GameBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addGroup(GameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Turn)
                    .addComponent(PlayerTurn))
                .addContainerGap(153, Short.MAX_VALUE))
            .addComponent(RoomTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GOMOKU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GameplayLayout.setVerticalGroup(
            GameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameplayLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(GOMOKU)
                .addGap(18, 18, 18)
                .addComponent(RoomTitle1)
                .addGroup(GameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameplayLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Turn)
                        .addGap(27, 27, 27)
                        .addComponent(PlayerTurn))
                    .addGroup(GameplayLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(GameBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Gomoku.add(Gameplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gomoku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gomoku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayGameButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayGameButtonMousePressed
        // TODO add your handling code here:java.awt.EventQueue.invokeLater(new Runnable() {
        if (!(InsertPort.getText().equals("") || InsertServerAddress.getText().equals("") || InsertNickname.getText().equals("") || InsertPort.getText().contains(",") || InsertServerAddress.getText().contains(",") || InsertNickname.getText().contains(","))){
            try {System.out.println(InsertPort.getText());
                cliSocket = new Socket(InsertServerAddress.getText(), Integer.parseInt(InsertPort.getText()));
        
                outToServer = new DataOutputStream(cliSocket.getOutputStream());
                inFromServer = new BufferedReader(new InputStreamReader(cliSocket.getInputStream()));
        
                outToServer.writeBytes(Nickname + '\n');
        
                String userId = inFromServer.readLine();
                idUser = Integer.parseInt(userId);
                
                 // Data yang dikirim ke server
                String sentence = "listRoom";
                outToServer.writeBytes(sentence + '\n');
        
                // Data yang diterima dari server
                String srvSentence = inFromServer.readLine();
                System.out.println("Sudah kekirim pesan ini: " + srvSentence);
                
                int i = 0;
                while (srvSentence.charAt(i) != ' '){
                    i++;
                }
                i++;
                String roomlist = "";
                while (i < srvSentence.length() && srvSentence.charAt(i) != ' ' && srvSentence.charAt(i) != '\n' && srvSentence.charAt(i) != '\0'){
                    roomlist = roomlist + srvSentence.substring(i,i+1);
                    System.out.println(roomlist);
                    i++;
                }
                
                int j = Integer.parseInt(roomlist);
                System.out.println(roomlist);
                RoomNameList = new ArrayList<String>();
                RoomMemberList = new ArrayList<Integer>();
                RoomCapacityList = new ArrayList<Integer>();
                RoomIDList = new ArrayList<Integer>();
                for(int k = 0; k < j; k++){
                    i++;
                    String _roomname = "";
                    while (srvSentence.charAt(i) != ' '){
                        _roomname = _roomname + srvSentence.substring(i,i+1);
                        i++;
                    }
                    System.out.println(_roomname);
                    i++;
                    String _roommember = "";
                    while (srvSentence.charAt(i) != ' '){
                        _roommember = _roommember + srvSentence.substring(i,i+1);
                        i++;
                    }
                    System.out.println(_roommember);
                    i++;
                    String _roomcapacity = "";
                    while (i < srvSentence.length() && srvSentence.charAt(i) != ' ' && srvSentence.charAt(i) != '\n'){
                        _roomcapacity = _roomcapacity + srvSentence.substring(i,i+1);
                        i++;
                    }
                    System.out.println(_roomcapacity);
                    i++;
                    String _roomID = "";
                    while (i < srvSentence.length() && srvSentence.charAt(i) != ' ' && srvSentence.charAt(i) != '\n'){
                        _roomID = _roomID + srvSentence.substring(i,i+1);
                        i++;
                    }
                    System.out.println(_roomID);
                    RoomNameList.add(_roomname);
                    RoomMemberList.add(Integer.parseInt(_roommember));
                    RoomCapacityList.add(Integer.parseInt(_roomcapacity));
                    RoomIDList.add(Integer.parseInt(_roomID));
                }
                InsideChooseRoomPane.setLayout(new BoxLayout(InsideChooseRoomPane, BoxLayout.X_AXIS));
                InsideChooseRoomPane.setBackground(new Color(153,204,255));
                ChooseRoomPane.setViewportView(InsideChooseRoomPane);
                for (i = 0; i < RoomNameList.size(); i++){
                    JPanel panelRoom = new JPanel();
                    final String crn = RoomNameList.get(i);
                    final int crnid = RoomIDList.get(i);
                    panelRoom.setLayout(new BoxLayout(panelRoom, BoxLayout.Y_AXIS));
                    panelRoom.setBackground(new Color(153,204,255));
                    JLabel doorRoom = new JLabel(crn+"door");
                    doorRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/door.png")));
                    doorRoom.setText("");
                    doorRoom.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                            Roomname = crn;
                            RoomID = crnid;
                            doorRoomMousePressed(evt);
                        }
                    });
                    JLabel namaRoom = new JLabel("\n      "+RoomNameList.get(i)+" ("+RoomMemberList.get(i)+"/"+RoomCapacityList.get(i)+")");
                    panelRoom.add(doorRoom);
                    panelRoom.add(namaRoom);
                    InsideChooseRoomPane.add(panelRoom);
                    ChooseRoomPane.repaint();
                    ChooseRoomPane.revalidate();
                }
                Nickname = InsertNickname.getText();
                MenuAwal.setVisible(false);
                PilihRoom.setVisible(true);
                MasukRoom.setVisible(false);
                Gameplay.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Gomoku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_PlayGameButtonMousePressed

    private void CreateRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRoomButtonActionPerformed
        // TODO add your handling code here:
        if (!(InsertRoomName.getText().equals("") || InsertMaxPlayer.getText().equals("") || InsertRoomName.getText().contains(","))){
            Roomname = InsertRoomName.getText();
            //ngirim ke server
            //dapetin jawaban serverInsideChooseRoomPane.setLayout(new BoxLayout(InsideChooseRoomPane, BoxLayout.X_AXIS));
            try {
                System.out.println(InsertPort.getText());
                cliSocket = new Socket(InsertServerAddress.getText(), Integer.parseInt(InsertPort.getText()));
        
                outToServer = new DataOutputStream(cliSocket.getOutputStream());
                inFromServer = new BufferedReader(new InputStreamReader(cliSocket.getInputStream()));
        
                outToServer.writeBytes(Nickname + '\n');
        
                String userId = inFromServer.readLine();
                idUser = Integer.parseInt(userId);
                
                 // Data yang dikirim ke server
                String sentence = "createroom " + InsertRoomName.getText() + " " + InsertMaxPlayer.getText();
                outToServer.writeBytes(sentence + '\n');
        
                // Data yang diterima dari server
                String srvSentence = inFromServer.readLine();
                System.out.println("Sudah kekirim pesan ini: " + srvSentence);
                int i = 0;
                while (srvSentence.charAt(i) != ' '){
                    i++;
                }
                
                if (srvSentence.substring(0, i).equals("createSuccess")){
                    RoomMember = new ArrayList<String>();
                    RoomMember.add(Nickname);
                    InsidePlayerListPane.setLayout(new BoxLayout(InsidePlayerListPane, BoxLayout.X_AXIS));
                    InsidePlayerListPane.setBackground(new Color(153,204,255));
                    PlayerListPane.setViewportView(InsidePlayerListPane);
                    for ( i = 0; i < RoomMember.size(); i++){
                        JPanel panelRoom = new JPanel();
                        final String crn = RoomMember.get(i);
                        panelRoom.setLayout(new BoxLayout(panelRoom, BoxLayout.Y_AXIS));
                        panelRoom.setBackground(new Color(153,204,255));
                        JLabel playerBaduk = new JLabel(crn+"baduk");
                        playerBaduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/player"+(i+1)+".png")));
                        playerBaduk.setText("");
                        JLabel namaPlayer = new JLabel("\n      "+crn);
                        panelRoom.add(playerBaduk);
                        panelRoom.add(namaPlayer);
                        InsidePlayerListPane.add(panelRoom);
                        PlayerListPane.repaint();
                        PlayerListPane.revalidate();
                    }
                    RoomTitle.setText(Roomname);
                    if (RoomMember.size() >= 3) StartGameButtonDummy.setVisible(false);
                    MenuAwal.setVisible(false);
                    PilihRoom.setVisible(false);
                    MasukRoom.setVisible(true);
                    Gameplay.setVisible(false);
                }
            } catch (IOException ex) {
                Logger.getLogger(Gomoku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CreateRoomButtonActionPerformed

    private Color getColor(int k){
                Color x;
                if (k == 1) x =  new Color(255,0,0);
                else if (k == 2) x =  new Color(255,255,0);
                else if (k == 3) x =  new Color(0,0,255);
                else if (k == 4) x =  new Color(255,127,0);
                else if (k == 5) x =  new Color(255,0,255);
                else if (k == 6) x =  new Color(0,255,255);
                else if (k == 7) x =  new Color(127,127,0);
                else if (k == 8) x =  new Color(0,0,0);
                else if (k == 9) x =  new Color(127,127,127);
                else if (k == 10) x =  new Color(255,255,255);
                else  x = new Color(200,200,200);
        return x;
    }
    
    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        // TODO add your handling code here:
        WhoseTurn = Nickname;
        RoomTitle1.setText(Roomname);
        PlayerTurn.setText(WhoseTurn);
        createBoard();
        MenuAwal.setVisible(false);
        PilihRoom.setVisible(false);
        MasukRoom.setVisible(false);
        Gameplay.setVisible(true);
    }//GEN-LAST:event_StartGameButtonActionPerformed

    private void createBoard(){
        GameBoard.setLayout(new BoxLayout(GameBoard, BoxLayout.X_AXIS));
        for (int i = 0; i < 20; i++){
            final int ordinat = i;
            JPanel panelRoom = new JPanel();
            panelRoom.setLayout(new BoxLayout(panelRoom, BoxLayout.Y_AXIS));
            for (int j = 0; j < 20; j++){
                final int axis = j;
                BoardUI[i][j] = new JButton();
                BoardUI[i][j].setText("");
                BoardUI[i][j].setPreferredSize(new Dimension(20,20));
                BoardUI[i][j].setBackground(new Color(200,200,200));
                BoardUI[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        NewMove[0] = ordinat; NewMove[1] = axis;
                        buttonBoardPressed(evt);
                    }
                });
                panelRoom.add(BoardUI[i][j]);
            }
            GameBoard.add(panelRoom);
        }
    }
    
    private void buttonBoardPressed(java.awt.event.MouseEvent evt){
        Board[NewMove[0]][NewMove[1]] = RoomMember.indexOf(WhoseTurn) + 1;
        BoardUI[NewMove[0]][NewMove[1]].setBackground(getColor(RoomMember.indexOf(WhoseTurn) + 1));
    }
    
    private void doorRoomMousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        //ngirim ke server
        //dapetin jawaban server
        try {
                System.out.println(InsertPort.getText());
                cliSocket = new Socket(InsertServerAddress.getText(), Integer.parseInt(InsertPort.getText()));
        
                outToServer = new DataOutputStream(cliSocket.getOutputStream());
                inFromServer = new BufferedReader(new InputStreamReader(cliSocket.getInputStream()));
        
                outToServer.writeBytes(Nickname + '\n');
        
                String userId = inFromServer.readLine();
                idUser = Integer.parseInt(userId);
                
                 // Data yang dikirim ke server
                String sentence = "selectroom " + RoomID;
                outToServer.writeBytes(sentence + '\n');
        
                // Data yang diterima dari server
                String srvSentence = inFromServer.readLine();
                System.out.println("Sudah kekirim pesan ini: " + srvSentence);
                int i = 0;
                while (srvSentence.charAt(i) != ' '){
                    i++;
                }
                i++;
                String roomlist = "";
                while (i < srvSentence.length() && srvSentence.charAt(i) != ' ' && srvSentence.charAt(i) != '\n' && srvSentence.charAt(i) != '\0'){
                    
                    System.out.println(i);
                    roomlist = roomlist + srvSentence.substring(i,i+1);
                    System.out.println(roomlist);
                    i++;
                }
                
                int j = Integer.parseInt(roomlist);
                System.out.println(roomlist);
                RoomMember = new ArrayList<String>();
                for(int k = 0; k < j; k++){
                    i++;
                    String _roommember = "";
                    while (i < srvSentence.length() && srvSentence.charAt(i) != ' ' && srvSentence.charAt(i) != '\n'){
                        _roommember = _roommember + srvSentence.substring(i,i+1);
                        i++;
                    }
                    System.out.println(_roommember);
                    RoomMember.add(_roommember);
                }
                
                InsidePlayerListPane.setLayout(new BoxLayout(InsidePlayerListPane, BoxLayout.X_AXIS));
                InsidePlayerListPane.setBackground(new Color(153,204,255));
                PlayerListPane.setViewportView(InsidePlayerListPane);
                for (i = 0; i < RoomMember.size(); i++){
                    JPanel panelRoom = new JPanel();
                    final String crn = RoomMember.get(i);
                    panelRoom.setLayout(new BoxLayout(panelRoom, BoxLayout.Y_AXIS));
                    panelRoom.setBackground(new Color(153,204,255));
                    JLabel playerBaduk = new JLabel(crn+"baduk");
                    playerBaduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/player"+(i+1)+".png")));
                    playerBaduk.setText("");
                    JLabel namaPlayer = new JLabel("\n      "+crn);
                    panelRoom.add(playerBaduk);
                    panelRoom.add(namaPlayer);
                    InsidePlayerListPane.add(panelRoom);
                    PlayerListPane.repaint();
                    PlayerListPane.revalidate();
                }
                RoomTitle.setText(Roomname);
                if (RoomMember.size() >= 3) StartGameButtonDummy.setVisible(false);
                MenuAwal.setVisible(false);
                PilihRoom.setVisible(false);
                MasukRoom.setVisible(true);
                Gameplay.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Gomoku.class.getName()).log(Level.SEVERE, null, ex);
            }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gomoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gomoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gomoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gomoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gomoku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChooseRoom;
    private javax.swing.JScrollPane ChooseRoomPane;
    private javax.swing.JLabel CreateRoom;
    private javax.swing.JButton CreateRoomButton;
    private javax.swing.JLabel CreateRoomDoor;
    private javax.swing.JLabel GOMOKU;
    private javax.swing.JPanel GameBoard;
    private javax.swing.JPanel Gameplay;
    private javax.swing.JLayeredPane Gomoku;
    private javax.swing.JTextField InsertMaxPlayer;
    private javax.swing.JTextField InsertNickname;
    private javax.swing.JTextField InsertPort;
    private javax.swing.JTextField InsertRoomName;
    private javax.swing.JTextField InsertServerAddress;
    private javax.swing.JPanel InsideChooseRoomPane;
    private javax.swing.JPanel InsidePlayerListPane;
    private javax.swing.JPanel MasukRoom;
    private javax.swing.JLabel MaxPlayer;
    private javax.swing.JPanel MenuAwal;
    private javax.swing.JLabel Or;
    private javax.swing.JPanel PilihRoom;
    private javax.swing.JLabel PlayGameButton;
    private javax.swing.JScrollPane PlayerListPane;
    private javax.swing.JLabel PlayerTurn;
    private javax.swing.JLabel Port;
    private javax.swing.JLabel Port1;
    private javax.swing.JLabel RoomName;
    private javax.swing.JLabel RoomTitle;
    private javax.swing.JLabel RoomTitle1;
    private javax.swing.JLabel ServerAddress;
    private javax.swing.JLayeredPane StartGame;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JButton StartGameButtonDummy;
    private javax.swing.JLabel Turn;
    // End of variables declaration//GEN-END:variables
}
